package cabin;

public enum ButtonType {
    ELECTRIC_MOTOR,
    WARNING_LIGHT,
    BLUE_LIGHT,
    HEAD_LIGHT,
    ROOF_LIGHT,
    FIRE_SELF_PROTECTION,
    LEFT_DOOR,
    RIGHT_DOOR,
    LEFT_JOYSTICK_LEFT,
    LEFT_JOYSTICK_RIGHT,
    LEFT_JOYSTICK_BACK,
    RIGHT_JOYSTICK_LEFT,
    RIGHT_JOYSTICK_RIGHT,
    RIGHT_JOYSTICK_BACK
}
